# Generated by Django 5.2.7 on 2025-11-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Alumno/a')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('book', models.CharField(max_length=500, verbose_name='Libro Solicitado')),
                ('date', models.CharField(max_length=100, verbose_name='Data da Petición')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprobado', 'Aprobado'), ('Mercado', 'Mercado'), ('Rexeitado', 'Rexeitado')], default='Pendente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitude de Libro',
                'verbose_name_plural': 'Solicitudes de Libros',
                'ordering': ['-created_at'],
            },
        ),
    ]
